secret_root: '{{ inventory_dir | realpath }}'
secret_name: 'secret'
secret: '{{ secret_root + "/" + secret_name }}'

wallabag_version: 2.4.3
wallabag_domain: "read.{{ domain }}"
wallabag_salt: "{{ lookup('password', secret + '/' + 'wallabag_salt', length=32) }}"
wallabag_db_username: wallabag
wallabag_db_password: "{{ lookup('password', secret + '/' + 'wallabag_db_password', length=32) }}"
wallabag_db_database: wallabag
