- name: Determine whether roundcube is configured
  stat: path=/var/www/roundcube/config.inc.php
  register: roundcube_config

- name: Install roundcube dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php
    - php-sqlite3
    - "{{ 'php-mcrypt' if ansible_distribution_major_version|int == 9 else 'libmcrypt-dev' }}"
    - php-gd
    - php-mbstring
    - php-pspell
    - php-intl
    - php-curl
    - php-xml
    - aspell
    - aspell-en
    - python3-mysqldb
    - git
  tags:
    - dependencies

- name: this is a newer version of debian so no php-mcrypt
  block:
    - name: ensure mcrypt dir is present
      file:
        path: /usr/lib/php/20180731/
        state: directory

    - name: install custom mcrypt
      copy:
        src: mcrypt.so
        dest: /usr/lib/php/20180731/mcrypt.so
        owner: root
        group: root
        mode: 0644
  when: ansible_distribution_major_version|int > 9

# - name: Clone roundcube
#   git: repo=https://github.com/roundcube/roundcubemail.git
#        dest=/var/www/roundcube
#        version={{ webmail_version }}
#        update=no
#        accept_hostkey=yes

# - name: Get Composer installer
#   get_url: url=https://getcomposer.org/installer
#            dest=/tmp/composer-installer

# - name: Copy composer configuration
#   copy: src=var_www_roundcube_composer.json dest=/var/www/roundcube/composer.json
#     owner=root
#     group=www-data
#     mode=0644

# - name: Install Composer
#   command: php /tmp/composer-installer
#            chdir=/root
#            creates=/root/composer.phar

# - name: Initialize composer
#   command: php /root/composer.phar install --no-dev
#            chdir=/var/www/roundcube
#            creates=/var/www/roundcube/vendor/autoload.php

# - name: Remove installer directory
#   file: path=/var/www/roundcube/installer state=absent

- name: Create Roundcube Dir
  file:
    path: /var/www/roundcube
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'

- name: Get Roundcube Release
  get_url:
    url: "https://github.com/roundcube/roundcubemail/releases/download/{{ webmail_version }}/roundcubemail-{{ webmail_version }}-complete.tar.gz"
    dest: /var/www/roundcube
  register: download

- name: Unarchive Roundcube
  unarchive:
    src: "/var/www/roundcube/roundcubemail-{{ webmail_version }}-complete.tar.gz"
    dest: /var/www/roundcube
    group: www-data
    extra_opts:
      - --strip-components=1
    copy: no
  when: download.changed

- name: Install Roundcube configuration
  template: src=var_www_roundcube_config_config.inc.j2 dest=/var/www/roundcube/config/config.inc.php

- name: Create db directory
  file: path=/decrypted/roundcube group=www-data mode=0775 state=directory

- name: Make logs and temp directories writable by web server
  file: path=/var/www/roundcube/{{ item }} mode=0775 state=directory
  with_items:
    - temp
    - logs

- name: Make roundcube directory accessible to web server
  file: path=/var/www/roundcube group=www-data recurse=yes state=directory
- name: Install sieve plugin configuration
  copy: src=var_www_roundcube_plugins_managesieve_config.inc.php
    dest=/var/www/roundcube/plugins/managesieve/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Install global sieve
  copy: src=var_www_roundcube_config_global.sieve
    dest=/var/www/roundcube/config/global.sieve
    owner=root
    group=www-data
    mode=0644

- name: Download carddav plugin
  get_url:
    url: https://github.com/mstilkerich/rcmcarddav/releases/download/v{{ carddav_version }}/carddav-v{{ carddav_version }}.tar.gz
    dest: /var/www/roundcube/plugins
  register: carddav_download

- name: Unarchive carddav
  unarchive:
    src: "/var/www/roundcube/plugins/carddav-v{{ carddav_version }}.tar.gz"
    dest: /var/www/roundcube/plugins
    group: www-data
    copy: no
  when: carddav_download.changed  

- name: Install carddav plugin configuration
  copy: src=var_www_roundcube_plugins_carddav_config.inc.php
    dest=/var/www/roundcube/plugins/carddav/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Clone Google 2-factor authentication plugin
  git: repo=https://github.com/alexandregz/twofactor_gauthenticator.git
       dest=/var/www/roundcube/plugins/twofactor_gauthenticator
       update=no
       accept_hostkey=yes  

- name: Install Google 2-factor authentication plugin configuration
  copy: src=var_www_roundcube_plugins_twofactor_gauthenticator_config.inc.php
    dest=/var/www/roundcube/plugins/twofactor_gauthenticator/config.inc.php
    owner=root
    group=www-data
    mode=0644

- name: Configure Apache for Roundcube
  template: src=etc_apache2_sites-available_roundcube.j2
    dest=/etc/apache2/sites-available/roundcube.conf
    group=root owner=root force=yes

- name: Enable Roundcube site
  command: a2ensite roundcube.conf creates=/etc/apache2/sites-enabled/roundcube.conf
  notify: restart apache
